Convert SCC AB document
metanorma/scc-ab-docs pull request #2
Opened 2022-11-15 22:57 UTC by manuelfuenmayor

Fixes https://github.com/metanorma/scc-ab-docs/issues/1

* I have compiled with ISO flavor to check the encoding.
* I'm not sure about the attribute configuration I used. Can you please take a look?

Thanks!

2022-11-16 02:54 UTC, ronaldtse requested changes

2022-11-16 02:54 UTC, ronaldtse commented on sources/SIRB_RG/sections/04-reqs_and_guidance.adoc
> +.REQUIREMENTS & GUIDANCE
@manuelfuenmayor sorry I forgot to specify -- we want to change this table into real clauses as in the following structure:

```
=== Consensus Process

The SDO shall provide a process to achieve consensus in the development of its standards under SCC's accreditation.

NOTE: Consensus does not imply unanimity.

NOTE: Sustained opposition is not intended to provide a  "`veto`" to any one stakeholder.
```

If there is "No guidance", write "NOTE: No guidance."

Thanks!

2022-11-16 03:34 UTC, manuelfuenmayor commented on sources/SIRB_RG/sections/04-reqs_and_guidance.adoc
> +.REQUIREMENTS & GUIDANCE
@ronaldtse, what about for cases like this:
![capture1](https://user-images.githubusercontent.com/33627611/202077250-8a873432-9ef6-4b43-8e91-04826f788810.PNG)

Should I do:
```adoc
=== References to Certification or Administrative Requirements

Administrative requirements relating to conformity assessment, marks
of conformity, or other non- technical issues should be presented
separately from technical requirements.
```

2022-11-16 03:55 UTC, manuelfuenmayor commented on sources/SIRB_RG/sections/04-reqs_and_guidance.adoc
> +.REQUIREMENTS & GUIDANCE
There is also this:

![capture2](https://user-images.githubusercontent.com/33627611/202079687-24cfa041-7f33-4da0-9d9c-3935e0f7f505.PNG)

It seems like these sub-sections don't have section titles.

2022-11-16 04:10 UTC, manuelfuenmayor commented on sources/SIRB_RG/sections/04-reqs_and_guidance.adoc
> +.REQUIREMENTS & GUIDANCE
I've done:
```adoc
[[sec_9.2.3]]
==== {blank}

No standard submitted...

NOTE: No guidance
```

2022-11-16 05:23 UTC, ronaldtse commented on sources/SIRB_RG/sections/04-reqs_and_guidance.adoc
> +.REQUIREMENTS & GUIDANCE
Agree with this.

2022-11-16 05:24 UTC, ronaldtse commented on sources/SIRB_RG/sections/04-reqs_and_guidance.adoc
> +.REQUIREMENTS & GUIDANCE
> @ronaldtse, what about for cases like this: ![capture1](https://user-images.githubusercontent.com/33627611/202077250-8a873432-9ef6-4b43-8e91-04826f788810.PNG)
> 
> Should I do:
> 
> ```
> === References to Certification or Administrative Requirements
> 
> Administrative requirements relating to conformity assessment, marks
> of conformity, or other non- technical issues should be presented
> separately from technical requirements.
> 
> NOTE: No requirement.
> ```

I think we should do this:

```adoc
=== References to Certification or Administrative Requirements

No requirement.

NOTE: Administrative requirements relating to conformity assessment, marks
of conformity, or other non- technical issues should be presented
separately from technical requirements.
```

2022-11-17 01:05 UTC, ronaldtse commented on sources/SIRB_RG/sections/04-reqs_and_guidance.adoc
> +.REQUIREMENTS & GUIDANCE
I've done the change.

2022-11-17 01:24 UTC, merged